version: "3.3"
services:
    lippia:
       image: crowdar/lippia:3.3.0.0-SNAPSHOT
       volumes:  
            - .:/opt/workspace/automation
       working_dir: /opt/workspace/automation
       environment:
            - WORKSPACE=/opt/workspace/automation
            - CUSTOM_COMMAND=mvn clean test -PSecuencial -Dcucumber.tags=@Sample -Denvironment=default
